name = "dashinfluence-forms"
main = "cloudflare-worker.js"
compatibility_date = "2024-01-01"

[env.production]
name = "dashinfluence-forms"

[env.production.vars]
ENVIRONMENT = "production"

# Environment variables will be set via wrangler secret command
# RESEND_API_KEY will be set as a secret 